05/03/2020 10:55:41 AM INFO autoreload 17536 18104 Watching for file changes with StatReloader
05/05/2020 03:11:56 PM WARNING log 17536 4808 Not Found: /media/images/preview/7_poppy2gif.gif
05/05/2020 03:11:56 PM WARNING log 17536 11968 Not Found: /media/images/preview/slack-django-large2.jpg
05/05/2020 03:11:56 PM WARNING log 17536 13868 Not Found: /media/images/preview/7_poppy.gif
05/05/2020 03:11:56 PM WARNING log 17536 18976 Not Found: /media/images/preview/mugatu-s-l640.jpg
05/05/2020 03:12:00 PM WARNING log 17536 18976 Not Found: /media/images/preview/7_poppy.gif
05/05/2020 03:12:00 PM WARNING log 17536 13868 Not Found: /media/images/preview/slack-django-large2.jpg
05/05/2020 03:12:00 PM WARNING log 17536 18976 Not Found: /media/images/preview/mugatu-s-l640.jpg
05/05/2020 03:25:42 PM WARNING log 17536 16488 Not Found: /media/images/preview/slack-django-large2.jpg
05/05/2020 03:25:42 PM WARNING log 17536 3608 Not Found: /media/images/preview/mugatu-s-l640.jpg
05/05/2020 03:25:42 PM WARNING log 17536 17612 Not Found: /media/images/preview/7_poppy2gif.gif
05/05/2020 03:31:03 PM ERROR log 17536 17612 Internal Server Error: /chisiamo
Traceback (most recent call last):
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\django\template\library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\webpack_loader\templatetags\webpack_loader.py", line 12, in render_bundle
    tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\webpack_loader\utils.py", line 45, in get_as_tags
    bundle = _get_bundle(bundle_name, extension, config)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\webpack_loader\utils.py", line 23, in _get_bundle
    bundle = get_loader(config).get_bundle(bundle_name)
  File "C:\Projects\DjangoREST\T190530\venv\lib\site-packages\webpack_loader\loader.py", line 97, in get_bundle
    raise WebpackError(error)
webpack_loader.exceptions.WebpackError: 
            ModuleParseError in 
            Module parse failed: Unexpected token (205:1)
File was processed with these loaders:
 * ./node_modules/vuetify-loader/lib/loader.js
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     }
|   }
> };
| 
            
